package com.money.feature.trade.application.memberpickup;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.money.contract.goods.CheckoutGoodsQuery; import com.money.contract.goods.CheckoutGoodsSnapshot; import com.money.dto.pos.MemberQuantityPickupReceiptVO;
import com.money.feature.trade.infrastructure.persistence.entity.*; import com.money.feature.trade.infrastructure.persistence.mapper.*; import com.money.web.exception.BaseException;
import lombok.RequiredArgsConstructor; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import java.util.*; import java.util.stream.Collectors;
/** Amount pickup uses the same non-sales receipt layout and setting as quantity pickup. */
@Service @RequiredArgsConstructor public class MemberAmountPickupReceiptService { private final OmsMemberAmountPickupMapper pickupMapper; private final OmsMemberAmountPickupItemMapper itemMapper; private final CheckoutGoodsQuery goodsQuery;
 public MemberQuantityPickupReceiptVO receipt(String pickupNo){ OmsMemberAmountPickup p=pickupMapper.selectOne(new LambdaQueryWrapper<OmsMemberAmountPickup>().eq(OmsMemberAmountPickup::getPickupNo,pickupNo)); if(p==null||!"COMPLETED".equals(p.getStatus()))throw new BaseException("会员提货单不存在或未完成"); List<OmsMemberAmountPickupItem> items=itemMapper.selectList(new LambdaQueryWrapper<OmsMemberAmountPickupItem>().eq(OmsMemberAmountPickupItem::getPickupNo,pickupNo)); if(items.isEmpty())throw new BaseException("会员提货单明细不存在"); Map<Long,CheckoutGoodsSnapshot> gs=goodsQuery.findByIds(items.stream().map(OmsMemberAmountPickupItem::getGoodsId).collect(Collectors.toList())); MemberQuantityPickupReceiptVO r=new MemberQuantityPickupReceiptVO();r.setPickupNo(pickupNo);r.setMemberId(p.getMemberId());r.setPickupTime(p.getCreateTime());r.setOperatorName(SecurityContextHolder.getContext().getAuthentication()==null?"System":SecurityContextHolder.getContext().getAuthentication().getName());r.setLines(items.stream().map(i->{CheckoutGoodsSnapshot g=gs.get(i.getGoodsId());if(g==null)throw new BaseException("提货商品不存在");MemberQuantityPickupReceiptVO.Line l=new MemberQuantityPickupReceiptVO.Line();l.setGoodsName(g.getName());l.setGoodsBarcode(g.getBarcode());l.setQuantity(i.getQuantity());return l;}).collect(Collectors.toList()));return r; }
}
