CREATE TABLE `ums_brand_benefit_tier` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `brand_id` varchar(50) NOT NULL,
  `tier_code` varchar(50) NOT NULL,
  `tier_name` varchar(100) NOT NULL,
  `configured_amount` decimal(12,2) NOT NULL,
  `pricing_level_code` varchar(50) NOT NULL,
  `rank_value` int NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `sort_no` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_by` varchar(32) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `update_by` varchar(32) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_brand_tier_code` (`brand_id`,`tier_code`),
  UNIQUE KEY `uk_brand_rank` (`brand_id`,`rank_value`),
  KEY `idx_brand_enabled_sort` (`brand_id`,`enabled`,`sort_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='品牌会员权益档位';

CREATE TABLE `ums_member_quantity_right` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint NOT NULL,
  `brand_id` varchar(50) NOT NULL,
  `goods_id` bigint NOT NULL,
  `source_order_no` varchar(32) NOT NULL,
  `source_order_detail_id` bigint DEFAULT NULL,
  `create_request_no` varchar(64) NOT NULL,
  `granted_quantity` int NOT NULL,
  `picked_quantity` int NOT NULL DEFAULT 0,
  `remaining_quantity` int NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ACTIVE',
  `create_by` varchar(32) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `update_by` varchar(32) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quantity_right_source` (`source_order_no`,`source_order_detail_id`),
  UNIQUE KEY `uk_quantity_right_create_request` (`create_request_no`),
  KEY `idx_quantity_right_member_goods` (`member_id`,`goods_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员商品提货数量权益';

CREATE TABLE `ums_member_quantity_right_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `right_id` bigint NOT NULL,
  `action` varchar(32) NOT NULL,
  `quantity_delta` int NOT NULL,
  `before_quantity` int NOT NULL,
  `after_quantity` int NOT NULL,
  `request_no` varchar(64) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_no` varchar(64) DEFAULT NULL,
  `operator_name` varchar(64) NOT NULL DEFAULT '',
  `reason` varchar(255) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quantity_right_request` (`right_id`,`request_no`),
  KEY `idx_quantity_right_log_time` (`right_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员商品提货数量权益流水';

CREATE TABLE `ums_member_amount_right` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint NOT NULL,
  `brand_id` varchar(50) NOT NULL,
  `tier_code_snapshot` varchar(50) NOT NULL,
  `tier_name_snapshot` varchar(100) NOT NULL,
  `pricing_level_code_snapshot` varchar(50) NOT NULL,
  `granted_amount` decimal(12,2) NOT NULL,
  `remaining_amount` decimal(12,2) NOT NULL,
  `source_receipt_no` varchar(64) NOT NULL,
  `create_request_no` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ACTIVE',
  `create_by` varchar(32) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `update_by` varchar(32) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_amount_right_receipt` (`source_receipt_no`),
  UNIQUE KEY `uk_amount_right_create_request` (`create_request_no`),
  KEY `idx_amount_right_member_brand` (`member_id`,`brand_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员品牌金额权益';

CREATE TABLE `ums_member_amount_right_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `right_id` bigint NOT NULL,
  `action` varchar(32) NOT NULL,
  `amount_delta` decimal(12,2) NOT NULL,
  `before_amount` decimal(12,2) NOT NULL,
  `after_amount` decimal(12,2) NOT NULL,
  `request_no` varchar(64) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_no` varchar(64) DEFAULT NULL,
  `operator_name` varchar(64) NOT NULL DEFAULT '',
  `reason` varchar(255) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_amount_right_request` (`right_id`,`request_no`),
  KEY `idx_amount_right_log_time` (`right_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员品牌金额权益流水';

CREATE TABLE `ums_member_target_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint NOT NULL,
  `brand_id` varchar(50) NOT NULL,
  `current_level_code_snapshot` varchar(50) DEFAULT NULL,
  `target_tier_code_snapshot` varchar(50) NOT NULL,
  `target_tier_name_snapshot` varchar(100) NOT NULL,
  `target_pricing_level_code_snapshot` varchar(50) NOT NULL,
  `target_rank_snapshot` int NOT NULL,
  `target_amount` decimal(12,2) NOT NULL,
  `progress_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(32) NOT NULL DEFAULT 'IN_PROGRESS',
  `confirmed_by` varchar(64) DEFAULT NULL,
  `confirmed_time` datetime DEFAULT NULL,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_request_no` varchar(64) NOT NULL,
  `create_by` varchar(32) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `update_by` varchar(32) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_target_plan_create_request` (`create_request_no`),
  KEY `idx_target_plan_member_brand` (`member_id`,`brand_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员品牌目标升级计划';

CREATE TABLE `ums_member_target_progress_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `action` varchar(32) NOT NULL,
  `amount_delta` decimal(12,2) NOT NULL,
  `before_amount` decimal(12,2) NOT NULL,
  `after_amount` decimal(12,2) NOT NULL,
  `request_no` varchar(64) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_no` varchar(64) DEFAULT NULL,
  `operator_name` varchar(64) NOT NULL DEFAULT '',
  `reason` varchar(255) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_target_plan_request` (`plan_id`,`request_no`),
  KEY `idx_target_progress_time` (`plan_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员品牌目标升级进度流水';
