package com.money.feature.ums.application.memberbenefit;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.money.contract.goods.*; import com.money.contract.member.*; import com.money.dto.memberbenefit.MemberAmountPackageDTO; import com.money.feature.ums.infrastructure.persistence.entity.UmsBrandAmountPackage; import com.money.feature.ums.infrastructure.persistence.mapper.UmsBrandAmountPackageMapper; import com.money.web.exception.BaseException; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor public class MemberAmountPackageService implements MemberAmountPackageQuery { private final UmsBrandAmountPackageMapper mapper; private final BrandSelectionQuery brands; private final BrandPricingLevelQuery levels;
 public List<MemberAmountPackageDTO> list(){return mapper.selectList(new LambdaQueryWrapper<UmsBrandAmountPackage>().orderByAsc(UmsBrandAmountPackage::getBrandId).orderByAsc(UmsBrandAmountPackage::getSortNo)).stream().map(this::dto).collect(Collectors.toList());}
 @Transactional(rollbackFor=Exception.class) public void save(MemberAmountPackageDTO d){ valid(d); UmsBrandAmountPackage r=d.getId()==null?new UmsBrandAmountPackage():need(d.getId()); r.setBrandId(d.getBrandId());r.setPackageCode(d.getPackageCode());r.setPackageName(d.getPackageName());r.setPurchaseAmount(d.getPurchaseAmount());r.setBenefitAmount(d.getBenefitAmount());r.setPricingLevelCode(d.getPricingLevelCode());r.setEnabled(d.getEnabled());r.setSortNo(d.getSortNo());r.setRemark(d.getRemark());r.setLegacyTierCode(d.getLegacyTierCode());if(d.getId()==null)mapper.insert(r);else mapper.updateById(r);}
 @Transactional(rollbackFor=Exception.class) public void delete(Long id){mapper.deleteById(id);}
 @Override public MemberAmountPackageSnapshot findEnabled(String b,String c){UmsBrandAmountPackage r=mapper.selectOne(new LambdaQueryWrapper<UmsBrandAmountPackage>().eq(UmsBrandAmountPackage::getBrandId,b).eq(UmsBrandAmountPackage::getPackageCode,c).eq(UmsBrandAmountPackage::getEnabled,true));if(r==null)return null;MemberAmountPackageSnapshot s=new MemberAmountPackageSnapshot();s.setBrandId(r.getBrandId());s.setPackageCode(r.getPackageCode());s.setPackageName(r.getPackageName());s.setPurchaseAmount(r.getPurchaseAmount());s.setBenefitAmount(r.getBenefitAmount());s.setPricingLevelCode(r.getPricingLevelCode());return s;}
 private void valid(MemberAmountPackageDTO d){if(!brands.listBrandSelections().stream().anyMatch(x->String.valueOf(x.getId()).equals(d.getBrandId())))throw new BaseException("品牌不存在");if(!levels.findEnabledLevelCodes(d.getBrandId()).contains(d.getPricingLevelCode()))throw new BaseException("价格档不属于该品牌定价策略");if(d.getPurchaseAmount().signum()<0||d.getBenefitAmount().signum()<=0||d.getSortNo()<0)throw new BaseException("包金额和排序不合法");LambdaQueryWrapper<UmsBrandAmountPackage> q=new LambdaQueryWrapper<UmsBrandAmountPackage>().eq(UmsBrandAmountPackage::getBrandId,d.getBrandId()).eq(UmsBrandAmountPackage::getPackageCode,d.getPackageCode());if(d.getId()!=null)q.ne(UmsBrandAmountPackage::getId,d.getId());if(mapper.selectCount(q)>0)throw new BaseException("同品牌权益包代码已存在");}
 private UmsBrandAmountPackage need(Long id){UmsBrandAmountPackage r=mapper.selectById(id);if(r==null)throw new BaseException("金额权益包不存在");return r;} private MemberAmountPackageDTO dto(UmsBrandAmountPackage r){MemberAmountPackageDTO d=new MemberAmountPackageDTO();d.setId(r.getId());d.setBrandId(r.getBrandId());d.setPackageCode(r.getPackageCode());d.setPackageName(r.getPackageName());d.setPurchaseAmount(r.getPurchaseAmount());d.setBenefitAmount(r.getBenefitAmount());d.setPricingLevelCode(r.getPricingLevelCode());d.setEnabled(r.getEnabled());d.setSortNo(r.getSortNo());d.setRemark(r.getRemark());d.setLegacyTierCode(r.getLegacyTierCode());return d;}}
