package com.money.feature.ums.application.memberbenefit;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.money.contract.member.MemberBenefitTradeHistoryQuery;
import com.money.dto.memberbenefit.MemberAssetBenefitHistoryVO;
import com.money.feature.ums.infrastructure.persistence.entity.*;
import com.money.feature.ums.infrastructure.persistence.mapper.*;
import com.money.mapper.UmsMemberLogMapper;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service;
import java.math.BigDecimal; import java.util.*;
/** UMS-owned read aggregation; it never writes legacy logs or invokes printing. */
@Service @RequiredArgsConstructor public class MemberAssetBenefitHistoryService {
 private final UmsMemberLogMapper assetLogMapper; private final UmsMemberQuantityRightMapper quantityMapper; private final UmsMemberQuantityRightLogMapper quantityLogMapper; private final UmsMemberAmountRightMapper amountMapper; private final UmsMemberAmountRightLogMapper amountLogMapper; private final UmsMemberTargetPlanMapper targetMapper; private final UmsMemberTargetProgressLogMapper targetLogMapper; private final MemberBenefitTradeHistoryQuery tradeHistory;
 public MemberAssetBenefitHistoryVO list(Long memberId) { List<MemberAssetBenefitHistoryVO.Record> out=new ArrayList<>(); if(memberId==null){MemberAssetBenefitHistoryVO r=new MemberAssetBenefitHistoryVO();r.setRecords(out);return r;}
  assetLogMapper.selectList(new LambdaQueryWrapper<UmsMemberLog>().eq(UmsMemberLog::getMemberId,memberId)).forEach(x->out.add(row(x.getCreateTime(),x.getOperateType(),x.getType(),x.getAmount(),null,x.getAfterAmount(),"元",x.getOrderNo(),x.getOperateType().equals("RECHARGE")?"RECHARGE":"ORDER",x.getOperateType().equals("RECHARGE")?"RECHARGE":"ORDER",null,null,x.getRemark())));
  Map<Long,UmsMemberQuantityRight> qs=new HashMap<>(); quantityMapper.selectList(new LambdaQueryWrapper<UmsMemberQuantityRight>().eq(UmsMemberQuantityRight::getMemberId,memberId)).forEach(x->qs.put(x.getId(),x)); quantityLogMapper.selectList(null).forEach(x->{if(qs.containsKey(x.getRightId()))out.add(row(x.getCreateTime(),x.getAction(),"QUANTITY",BigDecimal.valueOf(x.getQuantityDelta()),BigDecimal.valueOf(x.getBeforeQuantity()),BigDecimal.valueOf(x.getAfterQuantity()),"件",x.getSourceNo(),"PICKUP_DEDUCT".equals(x.getAction())?"QUANTITY_PICKUP":"ORDER","PICKUP_DEDUCT".equals(x.getAction())?"PICKUP":"ORDER",x.getOperatorName(),"COMPLETED",x.getReason()));});
  Map<Long,UmsMemberAmountRight> as=new HashMap<>(); amountMapper.selectList(new LambdaQueryWrapper<UmsMemberAmountRight>().eq(UmsMemberAmountRight::getMemberId,memberId)).forEach(x->as.put(x.getId(),x)); amountLogMapper.selectList(null).forEach(x->{if(as.containsKey(x.getRightId()))out.add(row(x.getCreateTime(),x.getAction(),"AMOUNT",x.getAmountDelta(),x.getBeforeAmount(),x.getAfterAmount(),"元",x.getSourceNo(),"AMOUNT_PICKUP","PICKUP",x.getOperatorName(),"COMPLETED",x.getReason()));});
  Map<Long,UmsMemberTargetPlan> ps=new HashMap<>(); targetMapper.selectList(new LambdaQueryWrapper<UmsMemberTargetPlan>().eq(UmsMemberTargetPlan::getMemberId,memberId)).forEach(x->ps.put(x.getId(),x)); targetLogMapper.selectList(null).forEach(x->{if(ps.containsKey(x.getPlanId()))out.add(row(x.getCreateTime(),x.getAction(),"TARGET_PROGRESS",x.getAmountDelta(),x.getBeforeAmount(),x.getAfterAmount(),"进度",x.getSourceNo(),"TARGET",null,x.getOperatorName(),ps.get(x.getPlanId()).getStatus(),x.getReason()));});
  tradeHistory.listByMember(memberId).getRecords().forEach(x->out.add(row(x.getCreateTime(),x.getRecordType(),"TRADE_DOCUMENT",x.getAmount(),null,null,"元",x.getReferenceNo(),x.getRecordType(),null,null,x.getStatus(),x.getSourceNo()))); out.sort(Comparator.comparing(MemberAssetBenefitHistoryVO.Record::getCreateTime,Comparator.nullsLast(Comparator.reverseOrder()))); MemberAssetBenefitHistoryVO r=new MemberAssetBenefitHistoryVO();r.setRecords(out);return r; }
 private MemberAssetBenefitHistoryVO.Record row(java.time.LocalDateTime t,String b,String d,BigDecimal x,BigDecimal before,BigDecimal after,String u,String n,String type,String target,String op,String status,String s){MemberAssetBenefitHistoryVO.Record r=new MemberAssetBenefitHistoryVO.Record();r.setCreateTime(t);r.setBusinessType(b);r.setDimension(d);r.setDelta(x);r.setBeforeValue(before);r.setAfterValue(after);r.setUnit(u);r.setReferenceNo(n);r.setDocumentType(type);r.setDetailTarget(target);r.setOperatorName(op);r.setStatus(status);r.setSummary(s);return r;}
}
